item { 
	name:'Agree'
	id:1
}
item { 
	name:'Disagree'
	id:2
}
item { 
	name:'Eat'
	id:3
}
item { 
	name:'Going To'
	id:4
}
item { 
	name:'Hello'
	id:5
}
item { 
	name:'Help'
	id:6
}
item { 
	name:'Later'
	id:7
}
item { 
	name:'Me'
	id:8
}
item { 
	name:'More'
	id:9
}
item { 
	name:'No'
	id:10
}
item { 
	name:'Please'
	id:11
}
item { 
	name:'See You'
	id:12
}
item { 
	name:'Thank You'
	id:13
}
item { 
	name:'Yes'
	id:14
}
